    - name: Install Mysql database
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start Mysql Server
      shell: "service mysql start"
    - name: Ensure mysql is enabled to run on startup  
      service: name=mysql state=started enabled=true

    - name: Create Application database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create Database user
      mysql_user: 
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL,GRANT'
        state: present
        host: '%'